// shale.proto - the gRPC service exposed by every shale node.
//
// In v0.1, this is the only protocol the shale CLI uses to talk to a
// running shaled. Starting in v0.2 (multi-node), it ALSO serves as the
// inter-node forwarding protocol: when node A receives a Put for a key
// owned by node B, A forwards the operation to B via this same service.
// One protocol, two callers; keeps the wire surface small.
//
// Transactions reach the wire in v0.6 as the unary CommitCAS RPC, an
// optimistic-concurrency (read-set / write-set) commit pinned to a
// single shard owner. Earlier versions (v0.1 through v0.5) did NOT
// expose transactions: a streaming/interactive transaction RPC would
// have needed careful design around connection lifetime + idempotency +
// cross-shard rejection, and holding a backend writer open across client
// think-time is the throughput anti-pattern CAS exists to avoid. The CAS
// shape keeps the owner's transaction tiny and owner-local: no
// transaction is ever open across the network, so the disconnect /
// leak-guard complexity of an interactive proxy mostly evaporates.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: shale.proto

package shalepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ShaleNode_Put_FullMethodName              = "/shale.v1.ShaleNode/Put"
	ShaleNode_Get_FullMethodName              = "/shale.v1.ShaleNode/Get"
	ShaleNode_Delete_FullMethodName           = "/shale.v1.ShaleNode/Delete"
	ShaleNode_ScanPrefix_FullMethodName       = "/shale.v1.ShaleNode/ScanPrefix"
	ShaleNode_LocalScan_FullMethodName        = "/shale.v1.ShaleNode/LocalScan"
	ShaleNode_Topology_FullMethodName         = "/shale.v1.ShaleNode/Topology"
	ShaleNode_Stats_FullMethodName            = "/shale.v1.ShaleNode/Stats"
	ShaleNode_Ping_FullMethodName             = "/shale.v1.ShaleNode/Ping"
	ShaleNode_MigrateRange_FullMethodName     = "/shale.v1.ShaleNode/MigrateRange"
	ShaleNode_ProposeRebalance_FullMethodName = "/shale.v1.ShaleNode/ProposeRebalance"
	ShaleNode_CommitCAS_FullMethodName        = "/shale.v1.ShaleNode/CommitCAS"
	ShaleNode_ApplyBatch_FullMethodName       = "/shale.v1.ShaleNode/ApplyBatch"
	ShaleNode_ReshardControl_FullMethodName   = "/shale.v1.ShaleNode/ReshardControl"
	ShaleNode_GenState_FullMethodName         = "/shale.v1.ShaleNode/GenState"
)

// ShaleNodeClient is the client API for ShaleNode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ShaleNode is what a shaled process serves on its gRPC listen address.
// All methods are per-key operations or cluster-wide queries; nothing
// here is shard-aware on the wire (the server decides locally whether
// to handle a key or, in v0.2+, forward it).
type ShaleNodeClient interface {
	// Put stores value under key.
	Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error)
	// Get returns the value for key. If absent, the response has
	// not_found=true + an empty value (instead of a gRPC error code, so
	// callers don't have to distinguish "absent" from "transport error").
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	// Delete removes key. Idempotent: deleting an absent key succeeds.
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	// ScanPrefix server-streams every key/value pair whose key starts
	// with the given prefix, in key-ascending order. The stream closes
	// cleanly when the scan is exhausted.
	ScanPrefix(ctx context.Context, in *ScanPrefixRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ScanPrefixResponse], error)
	// LocalScan is an admin-only variant of ScanPrefix that bypasses
	// ring-based routing + reads keys directly from the receiving
	// node's local Backend. Cross-shard machinery in pkg/cluster
	// (Aggregate snapshotting, Stats keys_held) uses it to ask peers
	// "what's actually on YOUR disk" without the request being
	// re-routed through ownerOf, which would otherwise route everything
	// to whichever node owns the empty prefix.
	LocalScan(ctx context.Context, in *LocalScanRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LocalScanResponse], error)
	// Topology describes the current cluster membership + ring layout.
	// In v0.1 single-node mode, single_node=true + nodes contains exactly
	// this one node. In v0.2+ it reports the full memberlist view.
	Topology(ctx context.Context, in *TopologyRequest, opts ...grpc.CallOption) (*TopologyResponse, error)
	// Stats returns per-node counters: how many keys this node holds,
	// request counts since process start, and the node's mount-readiness
	// counts. COUNTERS ONLY - the node keeps no latency histogram, so no
	// percentiles are reported (see the reserved fields on StatsResponse).
	Stats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error)
	// Ping is a no-op round trip for liveness checks. Useful for the CLI
	// `shale ping` subcommand + for inter-node health probes later.
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	// MigrateRange is the v0.3 rebalancing transport. The destination
	// (the node whose ring now lists it as owner of the given partitions)
	// initiates the call; the source streams every key/value pair whose
	// shard key falls in any of the requested partitions, then closes
	// with a MigrationDone marker carrying the total key count + a
	// CRC32-based checksum of the concatenated key|value bytes.
	//
	// RangeSpec.ring_generation is carried on the wire for v0.4
	// forward-compatibility (a cluster-wide generation lands with the
	// gossip layer then); v0.3 nodes use per-node monotonic counters
	// that are NOT comparable across peers, so the source does NOT
	// enforce a freshness check on the value. Wrong-owner protection
	// comes from the forwarding loop-guard + the per-key migration
	// guards on the cluster's KV path.
	MigrateRange(ctx context.Context, in *RangeSpec, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MigrateChunk], error)
	// ProposeRebalance is the operator-facing path for the
	// `shale rebalance --dry-run | --apply | --cancel` subcommand. It
	// returns the per-partition plan the local node would execute against
	// the current ring (or the in-flight plan, if one is running). Exactly
	// one of dry_run / apply / cancel must be true; the server returns
	// InvalidArgument otherwise.
	ProposeRebalance(ctx context.Context, in *ProposeRebalanceRequest, opts ...grpc.CallOption) (*ProposeRebalanceResponse, error)
	// CommitCAS is the v0.6 optimistic-concurrency commit. The client reads
	// via normal Gets, computes locally with no writer held anywhere, then
	// ships a read-set (reads) + write-set (writes) in ONE unary call to the
	// owner of pin_key. The owner verifies it owns pin_key, opens ONE short
	// owner-local backend transaction, validates every ReadCheck (a mismatch
	// is a conflict, not an error), applies the write-set, and commits. A
	// conflict travels as the typed conflict bool on the response, NOT as a
	// gRPC error code (the same not-found-is-not-an-error convention Get
	// uses); a backend / ownership failure travels as the error string.
	CommitCAS(ctx context.Context, in *CommitCASRequest, opts ...grpc.CallOption) (*CommitCASResponse, error)
	// ApplyBatch is a cluster-internal, owner-to-replica RPC (never called
	// from outside the cluster). Like the forwarded/replica Put path it is
	// an apply-only fan-out: the owner has already validated + stamped a CAS
	// write-set and committed it locally, then ships the SAME encoded
	// envelopes to each of the R-1 other replicas via this call so the
	// transactional writes get the R-replica durability single-key writes
	// already have. The replica applies the whole batch in ONE local backend
	// transaction (no re-validation, no re-stamp, written verbatim) and
	// commits, rolling back on any error. It honors the per-key migration
	// guard the same way the replica Put path does: a batch key that is
	// migrating or being received returns codes.ResourceExhausted so the
	// owner's fan-out classifies it transient rather than a failure. No
	// ownership re-check beyond that guard.
	ApplyBatch(ctx context.Context, in *ApplyBatchRequest, opts ...grpc.CallOption) (*ApplyBatchResponse, error)
	// ReshardControl is the cluster-internal control RPC for the v0.8
	// multi-node doubling reshard (cluster-wide freeze barrier). The
	// COORDINATOR (the node where Reshard() was called on a multi-node
	// cluster) drives a 4-phase barrier over every node (including itself)
	// by calling this RPC once per phase: FREEZE -> BISECT -> FLIP ->
	// RESUME (or ABORT on any failure / timeout / membership change). It is
	// direct peer RPC, NOT gossip, because a barrier needs a synchronous ack
	// from every node, which gossip (eventually-consistent broadcast) cannot
	// give. Each phase handler is idempotent. The receiver acks success with
	// an empty error string; a phase failure travels as the error string so
	// the coordinator can ABORT the whole reshard. Never called from outside
	// the cluster (CLI callers use Reshard via the cluster surface, not this
	// wire method directly).
	ReshardControl(ctx context.Context, in *ReshardControlRequest, opts ...grpc.CallOption) (*ReshardControlResponse, error)
	// GenState is the cluster-internal generation-propagation RPC for the
	// v0.8 join-after-reshard fix. A node opening in multi-backend mode WITH
	// seeds (a JOINER, not the founder) calls this on a live seed exactly once
	// during Open - BEFORE it derives or mounts any unit - to learn the
	// cluster's live {generation, unit-count}, then seeds its own routing state
	// from the answer. Without this a fresh joiner starts at generation 0 and,
	// after the cluster has resharded, routes / owns keys at the WRONG
	// generation (orphaning acked writes: "forwarding loop refused: this node
	// does not own the key"). The responder returns its current genSnapshot()
	// {gen, count}. Because a membership change mid-reshard ABORTS the reshard,
	// a join only ever lands at a STABLE generation, so the answer is a single
	// coherent value (no mid-cutover straddle to reason about). Direct peer RPC,
	// NOT gossip: a joiner needs a definite generation before it can serve, a
	// guarantee an eventually-consistent broadcast cannot give. Never called
	// from outside the cluster.
	GenState(ctx context.Context, in *GenStateRequest, opts ...grpc.CallOption) (*GenStateResponse, error)
}

type shaleNodeClient struct {
	cc grpc.ClientConnInterface
}

func NewShaleNodeClient(cc grpc.ClientConnInterface) ShaleNodeClient {
	return &shaleNodeClient{cc}
}

func (c *shaleNodeClient) Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutResponse)
	err := c.cc.Invoke(ctx, ShaleNode_Put_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shaleNodeClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, ShaleNode_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shaleNodeClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, ShaleNode_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shaleNodeClient) ScanPrefix(ctx context.Context, in *ScanPrefixRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ScanPrefixResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ShaleNode_ServiceDesc.Streams[0], ShaleNode_ScanPrefix_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ScanPrefixRequest, ScanPrefixResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ShaleNode_ScanPrefixClient = grpc.ServerStreamingClient[ScanPrefixResponse]

func (c *shaleNodeClient) LocalScan(ctx context.Context, in *LocalScanRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LocalScanResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ShaleNode_ServiceDesc.Streams[1], ShaleNode_LocalScan_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LocalScanRequest, LocalScanResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ShaleNode_LocalScanClient = grpc.ServerStreamingClient[LocalScanResponse]

func (c *shaleNodeClient) Topology(ctx context.Context, in *TopologyRequest, opts ...grpc.CallOption) (*TopologyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TopologyResponse)
	err := c.cc.Invoke(ctx, ShaleNode_Topology_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shaleNodeClient) Stats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatsResponse)
	err := c.cc.Invoke(ctx, ShaleNode_Stats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shaleNodeClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, ShaleNode_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shaleNodeClient) MigrateRange(ctx context.Context, in *RangeSpec, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MigrateChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ShaleNode_ServiceDesc.Streams[2], ShaleNode_MigrateRange_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RangeSpec, MigrateChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ShaleNode_MigrateRangeClient = grpc.ServerStreamingClient[MigrateChunk]

func (c *shaleNodeClient) ProposeRebalance(ctx context.Context, in *ProposeRebalanceRequest, opts ...grpc.CallOption) (*ProposeRebalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProposeRebalanceResponse)
	err := c.cc.Invoke(ctx, ShaleNode_ProposeRebalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shaleNodeClient) CommitCAS(ctx context.Context, in *CommitCASRequest, opts ...grpc.CallOption) (*CommitCASResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitCASResponse)
	err := c.cc.Invoke(ctx, ShaleNode_CommitCAS_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shaleNodeClient) ApplyBatch(ctx context.Context, in *ApplyBatchRequest, opts ...grpc.CallOption) (*ApplyBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyBatchResponse)
	err := c.cc.Invoke(ctx, ShaleNode_ApplyBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shaleNodeClient) ReshardControl(ctx context.Context, in *ReshardControlRequest, opts ...grpc.CallOption) (*ReshardControlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReshardControlResponse)
	err := c.cc.Invoke(ctx, ShaleNode_ReshardControl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shaleNodeClient) GenState(ctx context.Context, in *GenStateRequest, opts ...grpc.CallOption) (*GenStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenStateResponse)
	err := c.cc.Invoke(ctx, ShaleNode_GenState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShaleNodeServer is the server API for ShaleNode service.
// All implementations must embed UnimplementedShaleNodeServer
// for forward compatibility.
//
// ShaleNode is what a shaled process serves on its gRPC listen address.
// All methods are per-key operations or cluster-wide queries; nothing
// here is shard-aware on the wire (the server decides locally whether
// to handle a key or, in v0.2+, forward it).
type ShaleNodeServer interface {
	// Put stores value under key.
	Put(context.Context, *PutRequest) (*PutResponse, error)
	// Get returns the value for key. If absent, the response has
	// not_found=true + an empty value (instead of a gRPC error code, so
	// callers don't have to distinguish "absent" from "transport error").
	Get(context.Context, *GetRequest) (*GetResponse, error)
	// Delete removes key. Idempotent: deleting an absent key succeeds.
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	// ScanPrefix server-streams every key/value pair whose key starts
	// with the given prefix, in key-ascending order. The stream closes
	// cleanly when the scan is exhausted.
	ScanPrefix(*ScanPrefixRequest, grpc.ServerStreamingServer[ScanPrefixResponse]) error
	// LocalScan is an admin-only variant of ScanPrefix that bypasses
	// ring-based routing + reads keys directly from the receiving
	// node's local Backend. Cross-shard machinery in pkg/cluster
	// (Aggregate snapshotting, Stats keys_held) uses it to ask peers
	// "what's actually on YOUR disk" without the request being
	// re-routed through ownerOf, which would otherwise route everything
	// to whichever node owns the empty prefix.
	LocalScan(*LocalScanRequest, grpc.ServerStreamingServer[LocalScanResponse]) error
	// Topology describes the current cluster membership + ring layout.
	// In v0.1 single-node mode, single_node=true + nodes contains exactly
	// this one node. In v0.2+ it reports the full memberlist view.
	Topology(context.Context, *TopologyRequest) (*TopologyResponse, error)
	// Stats returns per-node counters: how many keys this node holds,
	// request counts since process start, and the node's mount-readiness
	// counts. COUNTERS ONLY - the node keeps no latency histogram, so no
	// percentiles are reported (see the reserved fields on StatsResponse).
	Stats(context.Context, *StatsRequest) (*StatsResponse, error)
	// Ping is a no-op round trip for liveness checks. Useful for the CLI
	// `shale ping` subcommand + for inter-node health probes later.
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	// MigrateRange is the v0.3 rebalancing transport. The destination
	// (the node whose ring now lists it as owner of the given partitions)
	// initiates the call; the source streams every key/value pair whose
	// shard key falls in any of the requested partitions, then closes
	// with a MigrationDone marker carrying the total key count + a
	// CRC32-based checksum of the concatenated key|value bytes.
	//
	// RangeSpec.ring_generation is carried on the wire for v0.4
	// forward-compatibility (a cluster-wide generation lands with the
	// gossip layer then); v0.3 nodes use per-node monotonic counters
	// that are NOT comparable across peers, so the source does NOT
	// enforce a freshness check on the value. Wrong-owner protection
	// comes from the forwarding loop-guard + the per-key migration
	// guards on the cluster's KV path.
	MigrateRange(*RangeSpec, grpc.ServerStreamingServer[MigrateChunk]) error
	// ProposeRebalance is the operator-facing path for the
	// `shale rebalance --dry-run | --apply | --cancel` subcommand. It
	// returns the per-partition plan the local node would execute against
	// the current ring (or the in-flight plan, if one is running). Exactly
	// one of dry_run / apply / cancel must be true; the server returns
	// InvalidArgument otherwise.
	ProposeRebalance(context.Context, *ProposeRebalanceRequest) (*ProposeRebalanceResponse, error)
	// CommitCAS is the v0.6 optimistic-concurrency commit. The client reads
	// via normal Gets, computes locally with no writer held anywhere, then
	// ships a read-set (reads) + write-set (writes) in ONE unary call to the
	// owner of pin_key. The owner verifies it owns pin_key, opens ONE short
	// owner-local backend transaction, validates every ReadCheck (a mismatch
	// is a conflict, not an error), applies the write-set, and commits. A
	// conflict travels as the typed conflict bool on the response, NOT as a
	// gRPC error code (the same not-found-is-not-an-error convention Get
	// uses); a backend / ownership failure travels as the error string.
	CommitCAS(context.Context, *CommitCASRequest) (*CommitCASResponse, error)
	// ApplyBatch is a cluster-internal, owner-to-replica RPC (never called
	// from outside the cluster). Like the forwarded/replica Put path it is
	// an apply-only fan-out: the owner has already validated + stamped a CAS
	// write-set and committed it locally, then ships the SAME encoded
	// envelopes to each of the R-1 other replicas via this call so the
	// transactional writes get the R-replica durability single-key writes
	// already have. The replica applies the whole batch in ONE local backend
	// transaction (no re-validation, no re-stamp, written verbatim) and
	// commits, rolling back on any error. It honors the per-key migration
	// guard the same way the replica Put path does: a batch key that is
	// migrating or being received returns codes.ResourceExhausted so the
	// owner's fan-out classifies it transient rather than a failure. No
	// ownership re-check beyond that guard.
	ApplyBatch(context.Context, *ApplyBatchRequest) (*ApplyBatchResponse, error)
	// ReshardControl is the cluster-internal control RPC for the v0.8
	// multi-node doubling reshard (cluster-wide freeze barrier). The
	// COORDINATOR (the node where Reshard() was called on a multi-node
	// cluster) drives a 4-phase barrier over every node (including itself)
	// by calling this RPC once per phase: FREEZE -> BISECT -> FLIP ->
	// RESUME (or ABORT on any failure / timeout / membership change). It is
	// direct peer RPC, NOT gossip, because a barrier needs a synchronous ack
	// from every node, which gossip (eventually-consistent broadcast) cannot
	// give. Each phase handler is idempotent. The receiver acks success with
	// an empty error string; a phase failure travels as the error string so
	// the coordinator can ABORT the whole reshard. Never called from outside
	// the cluster (CLI callers use Reshard via the cluster surface, not this
	// wire method directly).
	ReshardControl(context.Context, *ReshardControlRequest) (*ReshardControlResponse, error)
	// GenState is the cluster-internal generation-propagation RPC for the
	// v0.8 join-after-reshard fix. A node opening in multi-backend mode WITH
	// seeds (a JOINER, not the founder) calls this on a live seed exactly once
	// during Open - BEFORE it derives or mounts any unit - to learn the
	// cluster's live {generation, unit-count}, then seeds its own routing state
	// from the answer. Without this a fresh joiner starts at generation 0 and,
	// after the cluster has resharded, routes / owns keys at the WRONG
	// generation (orphaning acked writes: "forwarding loop refused: this node
	// does not own the key"). The responder returns its current genSnapshot()
	// {gen, count}. Because a membership change mid-reshard ABORTS the reshard,
	// a join only ever lands at a STABLE generation, so the answer is a single
	// coherent value (no mid-cutover straddle to reason about). Direct peer RPC,
	// NOT gossip: a joiner needs a definite generation before it can serve, a
	// guarantee an eventually-consistent broadcast cannot give. Never called
	// from outside the cluster.
	GenState(context.Context, *GenStateRequest) (*GenStateResponse, error)
	mustEmbedUnimplementedShaleNodeServer()
}

// UnimplementedShaleNodeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedShaleNodeServer struct{}

func (UnimplementedShaleNodeServer) Put(context.Context, *PutRequest) (*PutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Put not implemented")
}
func (UnimplementedShaleNodeServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedShaleNodeServer) Delete(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedShaleNodeServer) ScanPrefix(*ScanPrefixRequest, grpc.ServerStreamingServer[ScanPrefixResponse]) error {
	return status.Error(codes.Unimplemented, "method ScanPrefix not implemented")
}
func (UnimplementedShaleNodeServer) LocalScan(*LocalScanRequest, grpc.ServerStreamingServer[LocalScanResponse]) error {
	return status.Error(codes.Unimplemented, "method LocalScan not implemented")
}
func (UnimplementedShaleNodeServer) Topology(context.Context, *TopologyRequest) (*TopologyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Topology not implemented")
}
func (UnimplementedShaleNodeServer) Stats(context.Context, *StatsRequest) (*StatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Stats not implemented")
}
func (UnimplementedShaleNodeServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedShaleNodeServer) MigrateRange(*RangeSpec, grpc.ServerStreamingServer[MigrateChunk]) error {
	return status.Error(codes.Unimplemented, "method MigrateRange not implemented")
}
func (UnimplementedShaleNodeServer) ProposeRebalance(context.Context, *ProposeRebalanceRequest) (*ProposeRebalanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProposeRebalance not implemented")
}
func (UnimplementedShaleNodeServer) CommitCAS(context.Context, *CommitCASRequest) (*CommitCASResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CommitCAS not implemented")
}
func (UnimplementedShaleNodeServer) ApplyBatch(context.Context, *ApplyBatchRequest) (*ApplyBatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyBatch not implemented")
}
func (UnimplementedShaleNodeServer) ReshardControl(context.Context, *ReshardControlRequest) (*ReshardControlResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReshardControl not implemented")
}
func (UnimplementedShaleNodeServer) GenState(context.Context, *GenStateRequest) (*GenStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenState not implemented")
}
func (UnimplementedShaleNodeServer) mustEmbedUnimplementedShaleNodeServer() {}
func (UnimplementedShaleNodeServer) testEmbeddedByValue()                   {}

// UnsafeShaleNodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShaleNodeServer will
// result in compilation errors.
type UnsafeShaleNodeServer interface {
	mustEmbedUnimplementedShaleNodeServer()
}

func RegisterShaleNodeServer(s grpc.ServiceRegistrar, srv ShaleNodeServer) {
	// If the following call panics, it indicates UnimplementedShaleNodeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ShaleNode_ServiceDesc, srv)
}

func _ShaleNode_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShaleNodeServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShaleNode_Put_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShaleNodeServer).Put(ctx, req.(*PutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShaleNode_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShaleNodeServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShaleNode_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShaleNodeServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShaleNode_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShaleNodeServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShaleNode_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShaleNodeServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShaleNode_ScanPrefix_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ScanPrefixRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ShaleNodeServer).ScanPrefix(m, &grpc.GenericServerStream[ScanPrefixRequest, ScanPrefixResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ShaleNode_ScanPrefixServer = grpc.ServerStreamingServer[ScanPrefixResponse]

func _ShaleNode_LocalScan_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LocalScanRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ShaleNodeServer).LocalScan(m, &grpc.GenericServerStream[LocalScanRequest, LocalScanResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ShaleNode_LocalScanServer = grpc.ServerStreamingServer[LocalScanResponse]

func _ShaleNode_Topology_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TopologyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShaleNodeServer).Topology(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShaleNode_Topology_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShaleNodeServer).Topology(ctx, req.(*TopologyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShaleNode_Stats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShaleNodeServer).Stats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShaleNode_Stats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShaleNodeServer).Stats(ctx, req.(*StatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShaleNode_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShaleNodeServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShaleNode_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShaleNodeServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShaleNode_MigrateRange_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RangeSpec)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ShaleNodeServer).MigrateRange(m, &grpc.GenericServerStream[RangeSpec, MigrateChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ShaleNode_MigrateRangeServer = grpc.ServerStreamingServer[MigrateChunk]

func _ShaleNode_ProposeRebalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProposeRebalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShaleNodeServer).ProposeRebalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShaleNode_ProposeRebalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShaleNodeServer).ProposeRebalance(ctx, req.(*ProposeRebalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShaleNode_CommitCAS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitCASRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShaleNodeServer).CommitCAS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShaleNode_CommitCAS_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShaleNodeServer).CommitCAS(ctx, req.(*CommitCASRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShaleNode_ApplyBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShaleNodeServer).ApplyBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShaleNode_ApplyBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShaleNodeServer).ApplyBatch(ctx, req.(*ApplyBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShaleNode_ReshardControl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReshardControlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShaleNodeServer).ReshardControl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShaleNode_ReshardControl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShaleNodeServer).ReshardControl(ctx, req.(*ReshardControlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShaleNode_GenState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShaleNodeServer).GenState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShaleNode_GenState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShaleNodeServer).GenState(ctx, req.(*GenStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ShaleNode_ServiceDesc is the grpc.ServiceDesc for ShaleNode service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShaleNode_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shale.v1.ShaleNode",
	HandlerType: (*ShaleNodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Put",
			Handler:    _ShaleNode_Put_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _ShaleNode_Get_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ShaleNode_Delete_Handler,
		},
		{
			MethodName: "Topology",
			Handler:    _ShaleNode_Topology_Handler,
		},
		{
			MethodName: "Stats",
			Handler:    _ShaleNode_Stats_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _ShaleNode_Ping_Handler,
		},
		{
			MethodName: "ProposeRebalance",
			Handler:    _ShaleNode_ProposeRebalance_Handler,
		},
		{
			MethodName: "CommitCAS",
			Handler:    _ShaleNode_CommitCAS_Handler,
		},
		{
			MethodName: "ApplyBatch",
			Handler:    _ShaleNode_ApplyBatch_Handler,
		},
		{
			MethodName: "ReshardControl",
			Handler:    _ShaleNode_ReshardControl_Handler,
		},
		{
			MethodName: "GenState",
			Handler:    _ShaleNode_GenState_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ScanPrefix",
			Handler:       _ShaleNode_ScanPrefix_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "LocalScan",
			Handler:       _ShaleNode_LocalScan_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "MigrateRange",
			Handler:       _ShaleNode_MigrateRange_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "shale.proto",
}
