// shale.proto - the gRPC service exposed by every shale node.
//
// In v0.1, this is the only protocol the shale CLI uses to talk to a
// running shaled. Starting in v0.2 (multi-node), it ALSO serves as the
// inter-node forwarding protocol: when node A receives a Put for a key
// owned by node B, A forwards the operation to B via this same service.
// One protocol, two callers; keeps the wire surface small.
//
// Transactions reach the wire in v0.6 as the unary CommitCAS RPC, an
// optimistic-concurrency (read-set / write-set) commit pinned to a
// single shard owner. Earlier versions (v0.1 through v0.5) did NOT
// expose transactions: a streaming/interactive transaction RPC would
// have needed careful design around connection lifetime + idempotency +
// cross-shard rejection, and holding a backend writer open across client
// think-time is the throughput anti-pattern CAS exists to avoid. The CAS
// shape keeps the owner's transaction tiny and owner-local: no
// transaction is ever open across the network, so the disconnect /
// leak-guard complexity of an interactive proxy mostly evaporates.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: shale.proto

package shalepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ReshardPhase is the barrier phase the coordinator is driving. The
// receiving node's per-phase handler is idempotent (a repeated FREEZE is
// a no-op while already frozen for the same target generation, etc.).
type ReshardPhase int32

const (
	// RESHARD_PHASE_UNSPECIFIED is the proto3 zero value; the server rejects
	// it with an error so a malformed request never silently no-ops.
	ReshardPhase_RESHARD_PHASE_UNSPECIFIED ReshardPhase = 0
	// FREEZE pauses writes cluster-wide: Put / Delete / Begin (and the CAS
	// commit write path) return a retryable error (codes.Unavailable) until
	// RESUME or ABORT. Reads continue, served from the live gen-g units.
	ReshardPhase_RESHARD_PHASE_FREEZE ReshardPhase = 1
	// BISECT runs the local per-node bisect under the freeze: for each gen-g
	// unit this node owns, copy its keys into fresh gen-(g+1) units K and
	// K+N (created in the shared backing). With writes frozen the copy is
	// static, so there is no catch-up window.
	ReshardPhase_RESHARD_PHASE_BISECT ReshardPhase = 2
	// FLIP atomically advances this node's genState to the target generation
	// (routing now resolves the 2N units) and retires its old gen-g units.
	// No node flips until every node has bisected; the freeze still holds.
	ReshardPhase_RESHARD_PHASE_FLIP ReshardPhase = 3
	// RESUME unfreezes: writes resume at the new generation. The 2N units
	// then redistribute across nodes via the Phase 3 lease handoff.
	ReshardPhase_RESHARD_PHASE_RESUME ReshardPhase = 4
	// ABORT is the fail-safe: unfreeze, discard any half-built gen-(g+1)
	// units (harmless, never routed), and STAY at the current generation.
	ReshardPhase_RESHARD_PHASE_ABORT ReshardPhase = 5
)

// Enum value maps for ReshardPhase.
var (
	ReshardPhase_name = map[int32]string{
		0: "RESHARD_PHASE_UNSPECIFIED",
		1: "RESHARD_PHASE_FREEZE",
		2: "RESHARD_PHASE_BISECT",
		3: "RESHARD_PHASE_FLIP",
		4: "RESHARD_PHASE_RESUME",
		5: "RESHARD_PHASE_ABORT",
	}
	ReshardPhase_value = map[string]int32{
		"RESHARD_PHASE_UNSPECIFIED": 0,
		"RESHARD_PHASE_FREEZE":      1,
		"RESHARD_PHASE_BISECT":      2,
		"RESHARD_PHASE_FLIP":        3,
		"RESHARD_PHASE_RESUME":      4,
		"RESHARD_PHASE_ABORT":       5,
	}
)

func (x ReshardPhase) Enum() *ReshardPhase {
	p := new(ReshardPhase)
	*p = x
	return p
}

func (x ReshardPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReshardPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_shale_proto_enumTypes[0].Descriptor()
}

func (ReshardPhase) Type() protoreflect.EnumType {
	return &file_shale_proto_enumTypes[0]
}

func (x ReshardPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReshardPhase.Descriptor instead.
func (ReshardPhase) EnumDescriptor() ([]byte, []int) {
	return file_shale_proto_rawDescGZIP(), []int{0}
}

// ReplicaUnitRef is the POSITION-ADDRESSED forward target (v0.8 Phase 2e,
// Option B overlap handoff). The plain forwarded ops carry ONLY the key, and
// the receiver re-resolves the unit+position from the key against its OWN
// live ring index. On the predecessor of a moving position that no longer
// yields the draining position (the position moved away in the ring), so the
// overlap forward instead carries the EXPLICIT ReplicaUnit (gen, unit,
// replica). When this field is set on a forwarded op, the predecessor's
// handler resolves mountMap[ru] DIRECTLY by that ru - explicitly willing to
// serve a Draining-phase entry - rather than re-deriving the position from
// its ring index. It is the ONLY proto change Phase 2e introduces. Absent
// (unset) on every non-overlap forward, so the existing key-only forwarding
// is unchanged.
type ReplicaUnitRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gen           uint64                 `protobuf:"varint,1,opt,name=gen,proto3" json:"gen,omitempty"`
	Unit          uint32                 `protobuf:"varint,2,opt,name=unit,proto3" json:"unit,omitempty"`
	Replica       uint32                 `protobuf:"varint,3,opt,name=replica,proto3" json:"replica,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicaUnitRef) Reset() {
	*x = ReplicaUnitRef{}
	mi := &file_shale_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicaUnitRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaUnitRef) ProtoMessage() {}

func (x *ReplicaUnitRef) ProtoReflect() protoreflect.Message {
	mi := &file_shale_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaUnitRef.ProtoReflect.Descriptor instead.
func (*ReplicaUnitRef) Descriptor() ([]byte, []int) {
	return file_shale_proto_rawDescGZIP(), []int{0}
}

func (x *ReplicaUnitRef) GetGen() uint64 {
	if x != nil {
		return x.Gen
	}
	return 0
}

func (x *ReplicaUnitRef) GetUnit() uint32 {
	if x != nil {
		return x.Unit
	}
	return 0
}

func (x *ReplicaUnitRef) GetReplica() uint32 {
	if x != nil {
		return x.Replica
	}
	return 0
}

type PutRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Key       []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value     []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Forwarded bool                   `protobuf:"varint,3,opt,name=forwarded,proto3" json:"forwarded,omitempty"`
	// ru, when set, position-addresses this forwarded write to a specific
	// Draining replica on the predecessor (Phase 2e overlap forward). Unset
	// on every ordinary forward.
	Ru            *ReplicaUnitRef `protobuf:"bytes,4,opt,name=ru,proto3" json:"ru,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_shale_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shale_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_shale_proto_rawDescGZIP(), []int{1}
}

func (x *PutRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *PutRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *PutRequest) GetForwarded() bool {
	if x != nil {
		return x.Forwarded
	}
	return false
}

func (x *PutRequest) GetRu() *ReplicaUnitRef {
	if x != nil {
		return x.Ru
	}
	return nil
}

type PutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	mi := &file_shale_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shale_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_shale_proto_rawDescGZIP(), []int{2}
}

type GetRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Key       []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Forwarded bool                   `protobuf:"varint,2,opt,name=forwarded,proto3" json:"forwarded,omitempty"`
	// ru: see PutRequest.ru. Position-addressed overlap forward (Phase 2e).
	Ru            *ReplicaUnitRef `protobuf:"bytes,3,opt,name=ru,proto3" json:"ru,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_shale_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shale_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_shale_proto_rawDescGZIP(), []int{3}
}

func (x *GetRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *GetRequest) GetForwarded() bool {
	if x != nil {
		return x.Forwarded
	}
	return false
}

func (x *GetRequest) GetRu() *ReplicaUnitRef {
	if x != nil {
		return x.Ru
	}
	return nil
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	NotFound      bool                   `protobuf:"varint,2,opt,name=not_found,json=notFound,proto3" json:"not_found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_shale_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shale_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_shale_proto_rawDescGZIP(), []int{4}
}

func (x *GetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetResponse) GetNotFound() bool {
	if x != nil {
		return x.NotFound
	}
	return false
}

type DeleteRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Key       []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Forwarded bool                   `protobuf:"varint,2,opt,name=forwarded,proto3" json:"forwarded,omitempty"`
	// ru: see PutRequest.ru. Position-addressed overlap forward (Phase 2e).
	Ru            *ReplicaUnitRef `protobuf:"bytes,3,opt,name=ru,proto3" json:"ru,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_shale_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shale_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_shale_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *DeleteRequest) GetForwarded() bool {
	if x != nil {
		return x.Forwarded
	}
	return false
}

func (x *DeleteRequest) GetRu() *ReplicaUnitRef {
	if x != nil {
		return x.Ru
	}
	return nil
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_shale_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shale_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_shale_proto_rawDescGZIP(), []int{6}
}

type ScanPrefixRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        []byte                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Forwarded     bool                   `protobuf:"varint,2,opt,name=forwarded,proto3" json:"forwarded,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanPrefixRequest) Reset() {
	*x = ScanPrefixRequest{}
	mi := &file_shale_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanPrefixRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanPrefixRequest) ProtoMessage() {}

func (x *ScanPrefixRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shale_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanPrefixRequest.ProtoReflect.Descriptor instead.
func (*ScanPrefixRequest) Descriptor() ([]byte, []int) {
	return file_shale_proto_rawDescGZIP(), []int{7}
}

func (x *ScanPrefixRequest) GetPrefix() []byte {
	if x != nil {
		return x.Prefix
	}
	return nil
}

func (x *ScanPrefixRequest) GetForwarded() bool {
	if x != nil {
		return x.Forwarded
	}
	return false
}

type ScanPrefixResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanPrefixResponse) Reset() {
	*x = ScanPrefixResponse{}
	mi := &file_shale_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanPrefixResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanPrefixResponse) ProtoMessage() {}

func (x *ScanPrefixResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shale_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanPrefixResponse.ProtoReflect.Descriptor instead.
func (*ScanPrefixResponse) Descriptor() ([]byte, []int) {
	return file_shale_proto_rawDescGZIP(), []int{8}
}

func (x *ScanPrefixResponse) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ScanPrefixResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type LocalScanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        []byte                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalScanRequest) Reset() {
	*x = LocalScanRequest{}
	mi := &file_shale_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalScanRequest) ProtoMessage() {}

func (x *LocalScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shale_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalScanRequest.ProtoReflect.Descriptor instead.
func (*LocalScanRequest) Descriptor() ([]byte, []int) {
	return file_shale_proto_rawDescGZIP(), []int{9}
}

func (x *LocalScanRequest) GetPrefix() []byte {
	if x != nil {
		return x.Prefix
	}
	return nil
}

type LocalScanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalScanResponse) Reset() {
	*x = LocalScanResponse{}
	mi := &file_shale_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalScanResponse) ProtoMessage() {}

func (x *LocalScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shale_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalScanResponse.ProtoReflect.Descriptor instead.
func (*LocalScanResponse) Descriptor() ([]byte, []int) {
	return file_shale_proto_rawDescGZIP(), []int{10}
}

func (x *LocalScanResponse) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *LocalScanResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type TopologyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopologyRequest) Reset() {
	*x = TopologyRequest{}
	mi := &file_shale_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopologyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopologyRequest) ProtoMessage() {}

func (x *TopologyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shale_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopologyRequest.ProtoReflect.Descriptor instead.
func (*TopologyRequest) Descriptor() ([]byte, []int) {
	return file_shale_proto_rawDescGZIP(), []int{11}
}

type TopologyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// node_id of the node that served this RPC (the local node).
	NodeId string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// single_node is true when this is a v0.1-style standalone node with
	// no peers. Callers can short-circuit ring-display logic in that case.
	SingleNode bool `protobuf:"varint,2,opt,name=single_node,json=singleNode,proto3" json:"single_node,omitempty"`
	// nodes is the full membership view as seen by this node. In v0.1
	// it contains a single entry (this node).
	Nodes         []*NodeInfo `protobuf:"bytes,3,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopologyResponse) Reset() {
	*x = TopologyResponse{}
	mi := &file_shale_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopologyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopologyResponse) ProtoMessage() {}

func (x *TopologyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shale_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopologyResponse.ProtoReflect.Descriptor instead.
func (*TopologyResponse) Descriptor() ([]byte, []int) {
	return file_shale_proto_rawDescGZIP(), []int{12}
}

func (x *TopologyResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *TopologyResponse) GetSingleNode() bool {
	if x != nil {
		return x.SingleNode
	}
	return false
}

func (x *TopologyResponse) GetNodes() []*NodeInfo {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type NodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	GrpcAddr      string                 `protobuf:"bytes,2,opt,name=grpc_addr,json=grpcAddr,proto3" json:"grpc_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_shale_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_shale_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_shale_proto_rawDescGZIP(), []int{13}
}

func (x *NodeInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeInfo) GetGrpcAddr() string {
	if x != nil {
		return x.GrpcAddr
	}
	return ""
}

type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_shale_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shale_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_shale_proto_rawDescGZIP(), []int{14}
}

type StatsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// keys_held is the number of keys the local Backend currently owns.
	// Computed via a prefix-scan of the empty prefix in v0.1; a future
	// version will switch to a maintained counter.
	KeysHeld uint64 `protobuf:"varint,1,opt,name=keys_held,json=keysHeld,proto3" json:"keys_held,omitempty"`
	// Lifetime request counters since process start.
	Puts    uint64 `protobuf:"varint,2,opt,name=puts,proto3" json:"puts,omitempty"`
	Gets    uint64 `protobuf:"varint,3,opt,name=gets,proto3" json:"gets,omitempty"`
	Deletes uint64 `protobuf:"varint,4,opt,name=deletes,proto3" json:"deletes,omitempty"`
	Scans   uint64 `protobuf:"varint,5,opt,name=scans,proto3" json:"scans,omitempty"`
	// Latency percentiles (milliseconds). Placeholders in v0.1 (zero);
	// wired up to a real histogram in v0.5 alongside the Prometheus
	// metrics work.
	LatencyMsP50  float64 `protobuf:"fixed64,6,opt,name=latency_ms_p50,json=latencyMsP50,proto3" json:"latency_ms_p50,omitempty"`
	LatencyMsP99  float64 `protobuf:"fixed64,7,opt,name=latency_ms_p99,json=latencyMsP99,proto3" json:"latency_ms_p99,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_shale_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shale_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_shale_proto_rawDescGZIP(), []int{15}
}

func (x *StatsResponse) GetKeysHeld() uint64 {
	if x != nil {
		return x.KeysHeld
	}
	return 0
}

func (x *StatsResponse) GetPuts() uint64 {
	if x != nil {
		return x.Puts
	}
	return 0
}

func (x *StatsResponse) GetGets() uint64 {
	if x != nil {
		return x.Gets
	}
	return 0
}

func (x *StatsResponse) GetDeletes() uint64 {
	if x != nil {
		return x.Deletes
	}
	return 0
}

func (x *StatsResponse) GetScans() uint64 {
	if x != nil {
		return x.Scans
	}
	return 0
}

func (x *StatsResponse) GetLatencyMsP50() float64 {
	if x != nil {
		return x.LatencyMsP50
	}
	return 0
}

func (x *StatsResponse) GetLatencyMsP99() float64 {
	if x != nil {
		return x.LatencyMsP99
	}
	return 0
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_shale_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shale_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_shale_proto_rawDescGZIP(), []int{16}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_shale_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shale_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_shale_proto_rawDescGZIP(), []int{17}
}

// RangeSpec identifies which partitions the destination claims it now
// owns + the ring generation the destination is reasoning from. The
// generation is monotonic + incremented per ring change so the source
// can detect stale requests during the brief windows when peers
// disagree about ownership.
type RangeSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// partition_ids the destination claims ownership of. The source
	// iterates its local Backend over keys whose shard key falls into
	// any of these partitions.
	PartitionIds []uint64 `protobuf:"varint,1,rep,packed,name=partition_ids,json=partitionIds,proto3" json:"partition_ids,omitempty"`
	// ring_generation is the destination's view of the ring at the
	// moment it issued the request. v0.3 nodes use per-node monotonic
	// counters that are NOT cluster-comparable, so the source does
	// NOT enforce a freshness check on this value (every stream is
	// accepted regardless). The field is carried on the wire for
	// v0.4 forward-compatibility: a gossiped cluster-wide generation
	// will land then + the source-side rejection of stale requests
	// can become meaningful.
	RingGeneration uint64 `protobuf:"varint,2,opt,name=ring_generation,json=ringGeneration,proto3" json:"ring_generation,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RangeSpec) Reset() {
	*x = RangeSpec{}
	mi := &file_shale_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RangeSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeSpec) ProtoMessage() {}

func (x *RangeSpec) ProtoReflect() protoreflect.Message {
	mi := &file_shale_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeSpec.ProtoReflect.Descriptor instead.
func (*RangeSpec) Descriptor() ([]byte, []int) {
	return file_shale_proto_rawDescGZIP(), []int{18}
}

func (x *RangeSpec) GetPartitionIds() []uint64 {
	if x != nil {
		return x.PartitionIds
	}
	return nil
}

func (x *RangeSpec) GetRingGeneration() uint64 {
	if x != nil {
		return x.RingGeneration
	}
	return 0
}

// MigrateChunk is one message in the server-streaming response. Each
// message is either a key/value pair or, exactly once at the end, a
// MigrationDone marker. Receivers MUST treat the stream as finished
// when they see a done body, even if more messages appear after.
type MigrateChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*MigrateChunk_Kv
	//	*MigrateChunk_Done
	Body          isMigrateChunk_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MigrateChunk) Reset() {
	*x = MigrateChunk{}
	mi := &file_shale_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrateChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrateChunk) ProtoMessage() {}

func (x *MigrateChunk) ProtoReflect() protoreflect.Message {
	mi := &file_shale_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrateChunk.ProtoReflect.Descriptor instead.
func (*MigrateChunk) Descriptor() ([]byte, []int) {
	return file_shale_proto_rawDescGZIP(), []int{19}
}

func (x *MigrateChunk) GetBody() isMigrateChunk_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *MigrateChunk) GetKv() *KeyValue {
	if x != nil {
		if x, ok := x.Body.(*MigrateChunk_Kv); ok {
			return x.Kv
		}
	}
	return nil
}

func (x *MigrateChunk) GetDone() *MigrationDone {
	if x != nil {
		if x, ok := x.Body.(*MigrateChunk_Done); ok {
			return x.Done
		}
	}
	return nil
}

type isMigrateChunk_Body interface {
	isMigrateChunk_Body()
}

type MigrateChunk_Kv struct {
	Kv *KeyValue `protobuf:"bytes,1,opt,name=kv,proto3,oneof"`
}

type MigrateChunk_Done struct {
	Done *MigrationDone `protobuf:"bytes,2,opt,name=done,proto3,oneof"`
}

func (*MigrateChunk_Kv) isMigrateChunk_Body() {}

func (*MigrateChunk_Done) isMigrateChunk_Body() {}

// KeyValue carries one migrated pair. Keys are raw bytes as stored in
// the source Backend; the destination writes them through its own
// Backend.Put unchanged.
type KeyValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyValue) Reset() {
	*x = KeyValue{}
	mi := &file_shale_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValue) ProtoMessage() {}

func (x *KeyValue) ProtoReflect() protoreflect.Message {
	mi := &file_shale_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValue.ProtoReflect.Descriptor instead.
func (*KeyValue) Descriptor() ([]byte, []int) {
	return file_shale_proto_rawDescGZIP(), []int{20}
}

func (x *KeyValue) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *KeyValue) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// MigrationDone is the terminal marker. total_keys is the number of
// KeyValue messages that preceded it on the stream; checksum is the
// CRC32 (IEEE polynomial) of the concatenated key|value bytes in the
// order they were sent. The destination recomputes the checksum as it
// receives and rolls back the range on mismatch.
type MigrationDone struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalKeys     uint64                 `protobuf:"varint,1,opt,name=total_keys,json=totalKeys,proto3" json:"total_keys,omitempty"`
	Checksum      []byte                 `protobuf:"bytes,2,opt,name=checksum,proto3" json:"checksum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MigrationDone) Reset() {
	*x = MigrationDone{}
	mi := &file_shale_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrationDone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrationDone) ProtoMessage() {}

func (x *MigrationDone) ProtoReflect() protoreflect.Message {
	mi := &file_shale_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrationDone.ProtoReflect.Descriptor instead.
func (*MigrationDone) Descriptor() ([]byte, []int) {
	return file_shale_proto_rawDescGZIP(), []int{21}
}

func (x *MigrationDone) GetTotalKeys() uint64 {
	if x != nil {
		return x.TotalKeys
	}
	return 0
}

func (x *MigrationDone) GetChecksum() []byte {
	if x != nil {
		return x.Checksum
	}
	return nil
}

// ProposeRebalanceRequest carries the operator's intent. Exactly one
// of dry_run / apply / cancel must be true; the server returns
// InvalidArgument otherwise.
type ProposeRebalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DryRun        bool                   `protobuf:"varint,1,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	Apply         bool                   `protobuf:"varint,2,opt,name=apply,proto3" json:"apply,omitempty"`
	Cancel        bool                   `protobuf:"varint,3,opt,name=cancel,proto3" json:"cancel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProposeRebalanceRequest) Reset() {
	*x = ProposeRebalanceRequest{}
	mi := &file_shale_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProposeRebalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposeRebalanceRequest) ProtoMessage() {}

func (x *ProposeRebalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shale_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposeRebalanceRequest.ProtoReflect.Descriptor instead.
func (*ProposeRebalanceRequest) Descriptor() ([]byte, []int) {
	return file_shale_proto_rawDescGZIP(), []int{22}
}

func (x *ProposeRebalanceRequest) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

func (x *ProposeRebalanceRequest) GetApply() bool {
	if x != nil {
		return x.Apply
	}
	return false
}

func (x *ProposeRebalanceRequest) GetCancel() bool {
	if x != nil {
		return x.Cancel
	}
	return false
}

// ProposeRebalanceResponse returns the per-partition plan the local
// node would execute (dry_run / apply) or has just cancelled (cancel).
type ProposeRebalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ranges        []*RangePlanItem       `protobuf:"bytes,1,rep,name=ranges,proto3" json:"ranges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProposeRebalanceResponse) Reset() {
	*x = ProposeRebalanceResponse{}
	mi := &file_shale_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProposeRebalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposeRebalanceResponse) ProtoMessage() {}

func (x *ProposeRebalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shale_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposeRebalanceResponse.ProtoReflect.Descriptor instead.
func (*ProposeRebalanceResponse) Descriptor() ([]byte, []int) {
	return file_shale_proto_rawDescGZIP(), []int{23}
}

func (x *ProposeRebalanceResponse) GetRanges() []*RangePlanItem {
	if x != nil {
		return x.Ranges
	}
	return nil
}

// RangePlanItem is one row of the rebalance plan: which partition,
// who owns it now, who would own it after the plan applies, and a
// rough size hint for operators eyeballing cost.
type RangePlanItem struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PartitionId       uint64                 `protobuf:"varint,1,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	CurrentOwner      string                 `protobuf:"bytes,2,opt,name=current_owner,json=currentOwner,proto3" json:"current_owner,omitempty"`
	ProposedOwner     string                 `protobuf:"bytes,3,opt,name=proposed_owner,json=proposedOwner,proto3" json:"proposed_owner,omitempty"`
	EstimatedKeyCount uint64                 `protobuf:"varint,4,opt,name=estimated_key_count,json=estimatedKeyCount,proto3" json:"estimated_key_count,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RangePlanItem) Reset() {
	*x = RangePlanItem{}
	mi := &file_shale_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RangePlanItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangePlanItem) ProtoMessage() {}

func (x *RangePlanItem) ProtoReflect() protoreflect.Message {
	mi := &file_shale_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangePlanItem.ProtoReflect.Descriptor instead.
func (*RangePlanItem) Descriptor() ([]byte, []int) {
	return file_shale_proto_rawDescGZIP(), []int{24}
}

func (x *RangePlanItem) GetPartitionId() uint64 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

func (x *RangePlanItem) GetCurrentOwner() string {
	if x != nil {
		return x.CurrentOwner
	}
	return ""
}

func (x *RangePlanItem) GetProposedOwner() string {
	if x != nil {
		return x.ProposedOwner
	}
	return ""
}

func (x *RangePlanItem) GetEstimatedKeyCount() uint64 {
	if x != nil {
		return x.EstimatedKeyCount
	}
	return 0
}

// CommitCASRequest carries one optimistic-concurrency commit. pin_key is
// the key that pinned the shard; the owner verifies it owns this key and
// does NOT re-check ownership per read/write key (the client's cross-shard
// guard already ensured every key shards to the same owner). reads is the
// read-set the owner re-validates; writes is the write-set the owner
// applies in order once validation passes.
type CommitCASRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	PinKey []byte                 `protobuf:"bytes,1,opt,name=pin_key,json=pinKey,proto3" json:"pin_key,omitempty"`
	// isolation_level mirrors backend.IsolationLevel
	// (0=SnapshotIsolation, 1=SerializableSnapshot). The owner opens its
	// local transaction at this level.
	IsolationLevel int32        `protobuf:"varint,2,opt,name=isolation_level,json=isolationLevel,proto3" json:"isolation_level,omitempty"`
	Reads          []*ReadCheck `protobuf:"bytes,3,rep,name=reads,proto3" json:"reads,omitempty"`
	Writes         []*WriteOp   `protobuf:"bytes,4,rep,name=writes,proto3" json:"writes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CommitCASRequest) Reset() {
	*x = CommitCASRequest{}
	mi := &file_shale_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitCASRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitCASRequest) ProtoMessage() {}

func (x *CommitCASRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shale_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitCASRequest.ProtoReflect.Descriptor instead.
func (*CommitCASRequest) Descriptor() ([]byte, []int) {
	return file_shale_proto_rawDescGZIP(), []int{25}
}

func (x *CommitCASRequest) GetPinKey() []byte {
	if x != nil {
		return x.PinKey
	}
	return nil
}

func (x *CommitCASRequest) GetIsolationLevel() int32 {
	if x != nil {
		return x.IsolationLevel
	}
	return 0
}

func (x *CommitCASRequest) GetReads() []*ReadCheck {
	if x != nil {
		return x.Reads
	}
	return nil
}

func (x *CommitCASRequest) GetWrites() []*WriteOp {
	if x != nil {
		return x.Writes
	}
	return nil
}

// ReadCheck is one entry in the read-set: the value the client observed
// for key at read time. The owner re-reads key inside its transaction and
// compares. expect_absent=true means the key must NOT exist (a found value
// is a conflict) and expected_value is ignored; otherwise the current
// value must match expected_value byte-for-byte.
type ReadCheck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	ExpectedValue []byte                 `protobuf:"bytes,2,opt,name=expected_value,json=expectedValue,proto3" json:"expected_value,omitempty"`
	ExpectAbsent  bool                   `protobuf:"varint,3,opt,name=expect_absent,json=expectAbsent,proto3" json:"expect_absent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadCheck) Reset() {
	*x = ReadCheck{}
	mi := &file_shale_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadCheck) ProtoMessage() {}

func (x *ReadCheck) ProtoReflect() protoreflect.Message {
	mi := &file_shale_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadCheck.ProtoReflect.Descriptor instead.
func (*ReadCheck) Descriptor() ([]byte, []int) {
	return file_shale_proto_rawDescGZIP(), []int{26}
}

func (x *ReadCheck) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ReadCheck) GetExpectedValue() []byte {
	if x != nil {
		return x.ExpectedValue
	}
	return nil
}

func (x *ReadCheck) GetExpectAbsent() bool {
	if x != nil {
		return x.ExpectAbsent
	}
	return false
}

// WriteOp is one entry in the write-set. delete=true deletes key (value is
// ignored); else it Puts value under key.
type WriteOp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Delete        bool                   `protobuf:"varint,3,opt,name=delete,proto3" json:"delete,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteOp) Reset() {
	*x = WriteOp{}
	mi := &file_shale_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteOp) ProtoMessage() {}

func (x *WriteOp) ProtoReflect() protoreflect.Message {
	mi := &file_shale_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteOp.ProtoReflect.Descriptor instead.
func (*WriteOp) Descriptor() ([]byte, []int) {
	return file_shale_proto_rawDescGZIP(), []int{27}
}

func (x *WriteOp) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *WriteOp) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *WriteOp) GetDelete() bool {
	if x != nil {
		return x.Delete
	}
	return false
}

// CommitCASResponse reports the outcome. committed, conflict, and error are
// mutually exclusive: exactly one is meaningful per response. A conflict is
// NOT an error: it is the expected OCC retry signal, so it travels as a
// typed bool rather than a gRPC error code.
type CommitCASResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Committed     bool                   `protobuf:"varint,1,opt,name=committed,proto3" json:"committed,omitempty"`
	Conflict      bool                   `protobuf:"varint,2,opt,name=conflict,proto3" json:"conflict,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitCASResponse) Reset() {
	*x = CommitCASResponse{}
	mi := &file_shale_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitCASResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitCASResponse) ProtoMessage() {}

func (x *CommitCASResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shale_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitCASResponse.ProtoReflect.Descriptor instead.
func (*CommitCASResponse) Descriptor() ([]byte, []int) {
	return file_shale_proto_rawDescGZIP(), []int{28}
}

func (x *CommitCASResponse) GetCommitted() bool {
	if x != nil {
		return x.Committed
	}
	return false
}

func (x *CommitCASResponse) GetConflict() bool {
	if x != nil {
		return x.Conflict
	}
	return false
}

func (x *CommitCASResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// ApplyBatchRequest carries one CAS write-set fan-out from owner to
// replica. The owner has already committed these envelopes locally; the
// replica applies the whole batch (all writes) in ONE local transaction,
// apply-only, and commits. Any error rolls the entire batch back.
type ApplyBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Writes        []*EnvelopeWrite       `protobuf:"bytes,1,rep,name=writes,proto3" json:"writes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyBatchRequest) Reset() {
	*x = ApplyBatchRequest{}
	mi := &file_shale_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyBatchRequest) ProtoMessage() {}

func (x *ApplyBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shale_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyBatchRequest.ProtoReflect.Descriptor instead.
func (*ApplyBatchRequest) Descriptor() ([]byte, []int) {
	return file_shale_proto_rawDescGZIP(), []int{29}
}

func (x *ApplyBatchRequest) GetWrites() []*EnvelopeWrite {
	if x != nil {
		return x.Writes
	}
	return nil
}

// EnvelopeWrite is one entry in the fan-out batch: a key plus its already
// Encode()d envelope (shared stamp + payload). An empty-payload envelope
// is a tombstone. The replica writes the envelope bytes verbatim and never
// re-stamps.
type EnvelopeWrite struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Envelope      []byte                 `protobuf:"bytes,2,opt,name=envelope,proto3" json:"envelope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvelopeWrite) Reset() {
	*x = EnvelopeWrite{}
	mi := &file_shale_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvelopeWrite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvelopeWrite) ProtoMessage() {}

func (x *EnvelopeWrite) ProtoReflect() protoreflect.Message {
	mi := &file_shale_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvelopeWrite.ProtoReflect.Descriptor instead.
func (*EnvelopeWrite) Descriptor() ([]byte, []int) {
	return file_shale_proto_rawDescGZIP(), []int{30}
}

func (x *EnvelopeWrite) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *EnvelopeWrite) GetEnvelope() []byte {
	if x != nil {
		return x.Envelope
	}
	return nil
}

// ApplyBatchResponse reports the outcome. A non-empty error means the
// replica failed to apply the batch and rolled back. A migration-guard
// rejection travels as a gRPC codes.ResourceExhausted error (transient),
// not in this field.
type ApplyBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyBatchResponse) Reset() {
	*x = ApplyBatchResponse{}
	mi := &file_shale_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyBatchResponse) ProtoMessage() {}

func (x *ApplyBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shale_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyBatchResponse.ProtoReflect.Descriptor instead.
func (*ApplyBatchResponse) Descriptor() ([]byte, []int) {
	return file_shale_proto_rawDescGZIP(), []int{31}
}

func (x *ApplyBatchResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// ReshardControlRequest carries one barrier phase + the target generation
// g+1 the coordinator is driving toward. target_gen lets a node reject a
// request that disagrees with its own current generation (a stale or
// crossed reshard) rather than apply it blindly.
type ReshardControlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phase         ReshardPhase           `protobuf:"varint,1,opt,name=phase,proto3,enum=shale.v1.ReshardPhase" json:"phase,omitempty"`
	TargetGen     uint64                 `protobuf:"varint,2,opt,name=target_gen,json=targetGen,proto3" json:"target_gen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReshardControlRequest) Reset() {
	*x = ReshardControlRequest{}
	mi := &file_shale_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReshardControlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReshardControlRequest) ProtoMessage() {}

func (x *ReshardControlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shale_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReshardControlRequest.ProtoReflect.Descriptor instead.
func (*ReshardControlRequest) Descriptor() ([]byte, []int) {
	return file_shale_proto_rawDescGZIP(), []int{32}
}

func (x *ReshardControlRequest) GetPhase() ReshardPhase {
	if x != nil {
		return x.Phase
	}
	return ReshardPhase_RESHARD_PHASE_UNSPECIFIED
}

func (x *ReshardControlRequest) GetTargetGen() uint64 {
	if x != nil {
		return x.TargetGen
	}
	return 0
}

// ReshardControlResponse is the node's ack. An empty error means the phase
// was applied (the barrier ack the coordinator waits for); a non-empty
// error means the node could not apply the phase, which the coordinator
// treats as an ABORT trigger.
type ReshardControlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReshardControlResponse) Reset() {
	*x = ReshardControlResponse{}
	mi := &file_shale_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReshardControlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReshardControlResponse) ProtoMessage() {}

func (x *ReshardControlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shale_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReshardControlResponse.ProtoReflect.Descriptor instead.
func (*ReshardControlResponse) Descriptor() ([]byte, []int) {
	return file_shale_proto_rawDescGZIP(), []int{33}
}

func (x *ReshardControlResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// GenStateRequest carries no parameters: the joiner just asks the seed for
// its current generation state. The seed answers from its own genSnapshot().
type GenStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenStateRequest) Reset() {
	*x = GenStateRequest{}
	mi := &file_shale_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenStateRequest) ProtoMessage() {}

func (x *GenStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shale_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenStateRequest.ProtoReflect.Descriptor instead.
func (*GenStateRequest) Descriptor() ([]byte, []int) {
	return file_shale_proto_rawDescGZIP(), []int{34}
}

// GenStateResponse carries the responder's live {generation, unit-count}.
// The joiner commits genState{gen: generation, count: unit_count, cutOver
// empty} before mounting any unit. unit_count is carried explicitly (rather
// than re-derived from the joiner's configured UnitCount doubled `generation`
// times) so the contract is unambiguous and a future non-doubling resize
// cannot silently desync the count from the generation.
type GenStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Generation    uint64                 `protobuf:"varint,1,opt,name=generation,proto3" json:"generation,omitempty"`
	UnitCount     uint32                 `protobuf:"varint,2,opt,name=unit_count,json=unitCount,proto3" json:"unit_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenStateResponse) Reset() {
	*x = GenStateResponse{}
	mi := &file_shale_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenStateResponse) ProtoMessage() {}

func (x *GenStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shale_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenStateResponse.ProtoReflect.Descriptor instead.
func (*GenStateResponse) Descriptor() ([]byte, []int) {
	return file_shale_proto_rawDescGZIP(), []int{35}
}

func (x *GenStateResponse) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *GenStateResponse) GetUnitCount() uint32 {
	if x != nil {
		return x.UnitCount
	}
	return 0
}

var File_shale_proto protoreflect.FileDescriptor

const file_shale_proto_rawDesc = "" +
	"\n" +
	"\vshale.proto\x12\bshale.v1\"P\n" +
	"\x0eReplicaUnitRef\x12\x10\n" +
	"\x03gen\x18\x01 \x01(\x04R\x03gen\x12\x12\n" +
	"\x04unit\x18\x02 \x01(\rR\x04unit\x12\x18\n" +
	"\areplica\x18\x03 \x01(\rR\areplica\"|\n" +
	"\n" +
	"PutRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x1c\n" +
	"\tforwarded\x18\x03 \x01(\bR\tforwarded\x12(\n" +
	"\x02ru\x18\x04 \x01(\v2\x18.shale.v1.ReplicaUnitRefR\x02ru\"\r\n" +
	"\vPutResponse\"f\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x1c\n" +
	"\tforwarded\x18\x02 \x01(\bR\tforwarded\x12(\n" +
	"\x02ru\x18\x03 \x01(\v2\x18.shale.v1.ReplicaUnitRefR\x02ru\"@\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\x12\x1b\n" +
	"\tnot_found\x18\x02 \x01(\bR\bnotFound\"i\n" +
	"\rDeleteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x1c\n" +
	"\tforwarded\x18\x02 \x01(\bR\tforwarded\x12(\n" +
	"\x02ru\x18\x03 \x01(\v2\x18.shale.v1.ReplicaUnitRefR\x02ru\"\x10\n" +
	"\x0eDeleteResponse\"I\n" +
	"\x11ScanPrefixRequest\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\fR\x06prefix\x12\x1c\n" +
	"\tforwarded\x18\x02 \x01(\bR\tforwarded\"<\n" +
	"\x12ScanPrefixResponse\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"*\n" +
	"\x10LocalScanRequest\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\fR\x06prefix\";\n" +
	"\x11LocalScanResponse\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"\x11\n" +
	"\x0fTopologyRequest\"v\n" +
	"\x10TopologyResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1f\n" +
	"\vsingle_node\x18\x02 \x01(\bR\n" +
	"singleNode\x12(\n" +
	"\x05nodes\x18\x03 \x03(\v2\x12.shale.v1.NodeInfoR\x05nodes\"@\n" +
	"\bNodeInfo\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\tgrpc_addr\x18\x02 \x01(\tR\bgrpcAddr\"\x0e\n" +
	"\fStatsRequest\"\xd0\x01\n" +
	"\rStatsResponse\x12\x1b\n" +
	"\tkeys_held\x18\x01 \x01(\x04R\bkeysHeld\x12\x12\n" +
	"\x04puts\x18\x02 \x01(\x04R\x04puts\x12\x12\n" +
	"\x04gets\x18\x03 \x01(\x04R\x04gets\x12\x18\n" +
	"\adeletes\x18\x04 \x01(\x04R\adeletes\x12\x14\n" +
	"\x05scans\x18\x05 \x01(\x04R\x05scans\x12$\n" +
	"\x0elatency_ms_p50\x18\x06 \x01(\x01R\flatencyMsP50\x12$\n" +
	"\x0elatency_ms_p99\x18\a \x01(\x01R\flatencyMsP99\"\r\n" +
	"\vPingRequest\"\x0e\n" +
	"\fPingResponse\"Y\n" +
	"\tRangeSpec\x12#\n" +
	"\rpartition_ids\x18\x01 \x03(\x04R\fpartitionIds\x12'\n" +
	"\x0fring_generation\x18\x02 \x01(\x04R\x0eringGeneration\"k\n" +
	"\fMigrateChunk\x12$\n" +
	"\x02kv\x18\x01 \x01(\v2\x12.shale.v1.KeyValueH\x00R\x02kv\x12-\n" +
	"\x04done\x18\x02 \x01(\v2\x17.shale.v1.MigrationDoneH\x00R\x04doneB\x06\n" +
	"\x04body\"2\n" +
	"\bKeyValue\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"J\n" +
	"\rMigrationDone\x12\x1d\n" +
	"\n" +
	"total_keys\x18\x01 \x01(\x04R\ttotalKeys\x12\x1a\n" +
	"\bchecksum\x18\x02 \x01(\fR\bchecksum\"`\n" +
	"\x17ProposeRebalanceRequest\x12\x17\n" +
	"\adry_run\x18\x01 \x01(\bR\x06dryRun\x12\x14\n" +
	"\x05apply\x18\x02 \x01(\bR\x05apply\x12\x16\n" +
	"\x06cancel\x18\x03 \x01(\bR\x06cancel\"K\n" +
	"\x18ProposeRebalanceResponse\x12/\n" +
	"\x06ranges\x18\x01 \x03(\v2\x17.shale.v1.RangePlanItemR\x06ranges\"\xae\x01\n" +
	"\rRangePlanItem\x12!\n" +
	"\fpartition_id\x18\x01 \x01(\x04R\vpartitionId\x12#\n" +
	"\rcurrent_owner\x18\x02 \x01(\tR\fcurrentOwner\x12%\n" +
	"\x0eproposed_owner\x18\x03 \x01(\tR\rproposedOwner\x12.\n" +
	"\x13estimated_key_count\x18\x04 \x01(\x04R\x11estimatedKeyCount\"\xaa\x01\n" +
	"\x10CommitCASRequest\x12\x17\n" +
	"\apin_key\x18\x01 \x01(\fR\x06pinKey\x12'\n" +
	"\x0fisolation_level\x18\x02 \x01(\x05R\x0eisolationLevel\x12)\n" +
	"\x05reads\x18\x03 \x03(\v2\x13.shale.v1.ReadCheckR\x05reads\x12)\n" +
	"\x06writes\x18\x04 \x03(\v2\x11.shale.v1.WriteOpR\x06writes\"i\n" +
	"\tReadCheck\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12%\n" +
	"\x0eexpected_value\x18\x02 \x01(\fR\rexpectedValue\x12#\n" +
	"\rexpect_absent\x18\x03 \x01(\bR\fexpectAbsent\"I\n" +
	"\aWriteOp\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x16\n" +
	"\x06delete\x18\x03 \x01(\bR\x06delete\"c\n" +
	"\x11CommitCASResponse\x12\x1c\n" +
	"\tcommitted\x18\x01 \x01(\bR\tcommitted\x12\x1a\n" +
	"\bconflict\x18\x02 \x01(\bR\bconflict\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"D\n" +
	"\x11ApplyBatchRequest\x12/\n" +
	"\x06writes\x18\x01 \x03(\v2\x17.shale.v1.EnvelopeWriteR\x06writes\"=\n" +
	"\rEnvelopeWrite\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x1a\n" +
	"\benvelope\x18\x02 \x01(\fR\benvelope\"*\n" +
	"\x12ApplyBatchResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"d\n" +
	"\x15ReshardControlRequest\x12,\n" +
	"\x05phase\x18\x01 \x01(\x0e2\x16.shale.v1.ReshardPhaseR\x05phase\x12\x1d\n" +
	"\n" +
	"target_gen\x18\x02 \x01(\x04R\ttargetGen\".\n" +
	"\x16ReshardControlResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"\x11\n" +
	"\x0fGenStateRequest\"Q\n" +
	"\x10GenStateResponse\x12\x1e\n" +
	"\n" +
	"generation\x18\x01 \x01(\x04R\n" +
	"generation\x12\x1d\n" +
	"\n" +
	"unit_count\x18\x02 \x01(\rR\tunitCount*\xac\x01\n" +
	"\fReshardPhase\x12\x1d\n" +
	"\x19RESHARD_PHASE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14RESHARD_PHASE_FREEZE\x10\x01\x12\x18\n" +
	"\x14RESHARD_PHASE_BISECT\x10\x02\x12\x16\n" +
	"\x12RESHARD_PHASE_FLIP\x10\x03\x12\x18\n" +
	"\x14RESHARD_PHASE_RESUME\x10\x04\x12\x17\n" +
	"\x13RESHARD_PHASE_ABORT\x10\x052\xb8\a\n" +
	"\tShaleNode\x122\n" +
	"\x03Put\x12\x14.shale.v1.PutRequest\x1a\x15.shale.v1.PutResponse\x122\n" +
	"\x03Get\x12\x14.shale.v1.GetRequest\x1a\x15.shale.v1.GetResponse\x12;\n" +
	"\x06Delete\x12\x17.shale.v1.DeleteRequest\x1a\x18.shale.v1.DeleteResponse\x12I\n" +
	"\n" +
	"ScanPrefix\x12\x1b.shale.v1.ScanPrefixRequest\x1a\x1c.shale.v1.ScanPrefixResponse0\x01\x12F\n" +
	"\tLocalScan\x12\x1a.shale.v1.LocalScanRequest\x1a\x1b.shale.v1.LocalScanResponse0\x01\x12A\n" +
	"\bTopology\x12\x19.shale.v1.TopologyRequest\x1a\x1a.shale.v1.TopologyResponse\x128\n" +
	"\x05Stats\x12\x16.shale.v1.StatsRequest\x1a\x17.shale.v1.StatsResponse\x125\n" +
	"\x04Ping\x12\x15.shale.v1.PingRequest\x1a\x16.shale.v1.PingResponse\x12=\n" +
	"\fMigrateRange\x12\x13.shale.v1.RangeSpec\x1a\x16.shale.v1.MigrateChunk0\x01\x12Y\n" +
	"\x10ProposeRebalance\x12!.shale.v1.ProposeRebalanceRequest\x1a\".shale.v1.ProposeRebalanceResponse\x12D\n" +
	"\tCommitCAS\x12\x1a.shale.v1.CommitCASRequest\x1a\x1b.shale.v1.CommitCASResponse\x12G\n" +
	"\n" +
	"ApplyBatch\x12\x1b.shale.v1.ApplyBatchRequest\x1a\x1c.shale.v1.ApplyBatchResponse\x12S\n" +
	"\x0eReshardControl\x12\x1f.shale.v1.ReshardControlRequest\x1a .shale.v1.ReshardControlResponse\x12A\n" +
	"\bGenState\x12\x19.shale.v1.GenStateRequest\x1a\x1a.shale.v1.GenStateResponseB.Z,github.com/Zamua/shale/pkg/rpc/proto;shalepbb\x06proto3"

var (
	file_shale_proto_rawDescOnce sync.Once
	file_shale_proto_rawDescData []byte
)

func file_shale_proto_rawDescGZIP() []byte {
	file_shale_proto_rawDescOnce.Do(func() {
		file_shale_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shale_proto_rawDesc), len(file_shale_proto_rawDesc)))
	})
	return file_shale_proto_rawDescData
}

var file_shale_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_shale_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_shale_proto_goTypes = []any{
	(ReshardPhase)(0),                // 0: shale.v1.ReshardPhase
	(*ReplicaUnitRef)(nil),           // 1: shale.v1.ReplicaUnitRef
	(*PutRequest)(nil),               // 2: shale.v1.PutRequest
	(*PutResponse)(nil),              // 3: shale.v1.PutResponse
	(*GetRequest)(nil),               // 4: shale.v1.GetRequest
	(*GetResponse)(nil),              // 5: shale.v1.GetResponse
	(*DeleteRequest)(nil),            // 6: shale.v1.DeleteRequest
	(*DeleteResponse)(nil),           // 7: shale.v1.DeleteResponse
	(*ScanPrefixRequest)(nil),        // 8: shale.v1.ScanPrefixRequest
	(*ScanPrefixResponse)(nil),       // 9: shale.v1.ScanPrefixResponse
	(*LocalScanRequest)(nil),         // 10: shale.v1.LocalScanRequest
	(*LocalScanResponse)(nil),        // 11: shale.v1.LocalScanResponse
	(*TopologyRequest)(nil),          // 12: shale.v1.TopologyRequest
	(*TopologyResponse)(nil),         // 13: shale.v1.TopologyResponse
	(*NodeInfo)(nil),                 // 14: shale.v1.NodeInfo
	(*StatsRequest)(nil),             // 15: shale.v1.StatsRequest
	(*StatsResponse)(nil),            // 16: shale.v1.StatsResponse
	(*PingRequest)(nil),              // 17: shale.v1.PingRequest
	(*PingResponse)(nil),             // 18: shale.v1.PingResponse
	(*RangeSpec)(nil),                // 19: shale.v1.RangeSpec
	(*MigrateChunk)(nil),             // 20: shale.v1.MigrateChunk
	(*KeyValue)(nil),                 // 21: shale.v1.KeyValue
	(*MigrationDone)(nil),            // 22: shale.v1.MigrationDone
	(*ProposeRebalanceRequest)(nil),  // 23: shale.v1.ProposeRebalanceRequest
	(*ProposeRebalanceResponse)(nil), // 24: shale.v1.ProposeRebalanceResponse
	(*RangePlanItem)(nil),            // 25: shale.v1.RangePlanItem
	(*CommitCASRequest)(nil),         // 26: shale.v1.CommitCASRequest
	(*ReadCheck)(nil),                // 27: shale.v1.ReadCheck
	(*WriteOp)(nil),                  // 28: shale.v1.WriteOp
	(*CommitCASResponse)(nil),        // 29: shale.v1.CommitCASResponse
	(*ApplyBatchRequest)(nil),        // 30: shale.v1.ApplyBatchRequest
	(*EnvelopeWrite)(nil),            // 31: shale.v1.EnvelopeWrite
	(*ApplyBatchResponse)(nil),       // 32: shale.v1.ApplyBatchResponse
	(*ReshardControlRequest)(nil),    // 33: shale.v1.ReshardControlRequest
	(*ReshardControlResponse)(nil),   // 34: shale.v1.ReshardControlResponse
	(*GenStateRequest)(nil),          // 35: shale.v1.GenStateRequest
	(*GenStateResponse)(nil),         // 36: shale.v1.GenStateResponse
}
var file_shale_proto_depIdxs = []int32{
	1,  // 0: shale.v1.PutRequest.ru:type_name -> shale.v1.ReplicaUnitRef
	1,  // 1: shale.v1.GetRequest.ru:type_name -> shale.v1.ReplicaUnitRef
	1,  // 2: shale.v1.DeleteRequest.ru:type_name -> shale.v1.ReplicaUnitRef
	14, // 3: shale.v1.TopologyResponse.nodes:type_name -> shale.v1.NodeInfo
	21, // 4: shale.v1.MigrateChunk.kv:type_name -> shale.v1.KeyValue
	22, // 5: shale.v1.MigrateChunk.done:type_name -> shale.v1.MigrationDone
	25, // 6: shale.v1.ProposeRebalanceResponse.ranges:type_name -> shale.v1.RangePlanItem
	27, // 7: shale.v1.CommitCASRequest.reads:type_name -> shale.v1.ReadCheck
	28, // 8: shale.v1.CommitCASRequest.writes:type_name -> shale.v1.WriteOp
	31, // 9: shale.v1.ApplyBatchRequest.writes:type_name -> shale.v1.EnvelopeWrite
	0,  // 10: shale.v1.ReshardControlRequest.phase:type_name -> shale.v1.ReshardPhase
	2,  // 11: shale.v1.ShaleNode.Put:input_type -> shale.v1.PutRequest
	4,  // 12: shale.v1.ShaleNode.Get:input_type -> shale.v1.GetRequest
	6,  // 13: shale.v1.ShaleNode.Delete:input_type -> shale.v1.DeleteRequest
	8,  // 14: shale.v1.ShaleNode.ScanPrefix:input_type -> shale.v1.ScanPrefixRequest
	10, // 15: shale.v1.ShaleNode.LocalScan:input_type -> shale.v1.LocalScanRequest
	12, // 16: shale.v1.ShaleNode.Topology:input_type -> shale.v1.TopologyRequest
	15, // 17: shale.v1.ShaleNode.Stats:input_type -> shale.v1.StatsRequest
	17, // 18: shale.v1.ShaleNode.Ping:input_type -> shale.v1.PingRequest
	19, // 19: shale.v1.ShaleNode.MigrateRange:input_type -> shale.v1.RangeSpec
	23, // 20: shale.v1.ShaleNode.ProposeRebalance:input_type -> shale.v1.ProposeRebalanceRequest
	26, // 21: shale.v1.ShaleNode.CommitCAS:input_type -> shale.v1.CommitCASRequest
	30, // 22: shale.v1.ShaleNode.ApplyBatch:input_type -> shale.v1.ApplyBatchRequest
	33, // 23: shale.v1.ShaleNode.ReshardControl:input_type -> shale.v1.ReshardControlRequest
	35, // 24: shale.v1.ShaleNode.GenState:input_type -> shale.v1.GenStateRequest
	3,  // 25: shale.v1.ShaleNode.Put:output_type -> shale.v1.PutResponse
	5,  // 26: shale.v1.ShaleNode.Get:output_type -> shale.v1.GetResponse
	7,  // 27: shale.v1.ShaleNode.Delete:output_type -> shale.v1.DeleteResponse
	9,  // 28: shale.v1.ShaleNode.ScanPrefix:output_type -> shale.v1.ScanPrefixResponse
	11, // 29: shale.v1.ShaleNode.LocalScan:output_type -> shale.v1.LocalScanResponse
	13, // 30: shale.v1.ShaleNode.Topology:output_type -> shale.v1.TopologyResponse
	16, // 31: shale.v1.ShaleNode.Stats:output_type -> shale.v1.StatsResponse
	18, // 32: shale.v1.ShaleNode.Ping:output_type -> shale.v1.PingResponse
	20, // 33: shale.v1.ShaleNode.MigrateRange:output_type -> shale.v1.MigrateChunk
	24, // 34: shale.v1.ShaleNode.ProposeRebalance:output_type -> shale.v1.ProposeRebalanceResponse
	29, // 35: shale.v1.ShaleNode.CommitCAS:output_type -> shale.v1.CommitCASResponse
	32, // 36: shale.v1.ShaleNode.ApplyBatch:output_type -> shale.v1.ApplyBatchResponse
	34, // 37: shale.v1.ShaleNode.ReshardControl:output_type -> shale.v1.ReshardControlResponse
	36, // 38: shale.v1.ShaleNode.GenState:output_type -> shale.v1.GenStateResponse
	25, // [25:39] is the sub-list for method output_type
	11, // [11:25] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_shale_proto_init() }
func file_shale_proto_init() {
	if File_shale_proto != nil {
		return
	}
	file_shale_proto_msgTypes[19].OneofWrappers = []any{
		(*MigrateChunk_Kv)(nil),
		(*MigrateChunk_Done)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shale_proto_rawDesc), len(file_shale_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shale_proto_goTypes,
		DependencyIndexes: file_shale_proto_depIdxs,
		EnumInfos:         file_shale_proto_enumTypes,
		MessageInfos:      file_shale_proto_msgTypes,
	}.Build()
	File_shale_proto = out.File
	file_shale_proto_goTypes = nil
	file_shale_proto_depIdxs = nil
}
